# set_property -dict { PACKAGE_PIN AF2  } [get_ports gtx_113_tx_p0]
# set_property -dict { PACKAGE_PIN AF1  } [get_ports gtx_113_tx_n0]
# set_property -dict { PACKAGE_PIN AD2  } [get_ports gtx_113_tx_p1]
# set_property -dict { PACKAGE_PIN AD1  } [get_ports gtx_113_tx_n1]
# set_property -dict { PACKAGE_PIN AB2  } [get_ports gtx_113_tx_p2]
# set_property -dict { PACKAGE_PIN AB1  } [get_ports gtx_113_tx_n2]
# set_property -dict { PACKAGE_PIN Y2   } [get_ports gtx_113_tx_p3]
# set_property -dict { PACKAGE_PIN Y1   } [get_ports gtx_113_tx_n3]

# set_property -dict { PACKAGE_PIN AB6  } [get_ports gtx_113_rx_p0]
# set_property -dict { PACKAGE_PIN AB5  } [get_ports gtx_113_rx_n0]
# set_property -dict { PACKAGE_PIN AA4  } [get_ports gtx_113_rx_p1]
# set_property -dict { PACKAGE_PIN AA3  } [get_ports gtx_113_rx_n1]
# set_property -dict { PACKAGE_PIN Y6   } [get_ports gtx_113_rx_p2]
# set_property -dict { PACKAGE_PIN Y5   } [get_ports gtx_113_rx_n2]
# set_property -dict { PACKAGE_PIN W4   } [get_ports gtx_113_rx_p3]
# set_property -dict { PACKAGE_PIN W3   } [get_ports gtx_113_rx_n3]


# set_property -dict { PACKAGE_PIN V2   } [get_ports gtx_114_tx_p0]
# set_property -dict { PACKAGE_PIN V1   } [get_ports gtx_114_tx_n0]
# set_property -dict { PACKAGE_PIN T2   } [get_ports gtx_114_tx_p1]
# set_property -dict { PACKAGE_PIN T1   } [get_ports gtx_114_tx_n1]
# set_property -dict { PACKAGE_PIN P2   } [get_ports gtx_114_tx_p2]
# set_property -dict { PACKAGE_PIN P1   } [get_ports gtx_114_tx_n2]
# set_property -dict { PACKAGE_PIN N4   } [get_ports gtx_114_tx_p3]
# set_property -dict { PACKAGE_PIN N3   } [get_ports gtx_114_tx_n3]

# set_property -dict { PACKAGE_PIN V6   } [get_ports gtx_114_rx_p0]
# set_property -dict { PACKAGE_PIN V5   } [get_ports gtx_114_rx_n0]
# set_property -dict { PACKAGE_PIN U4   } [get_ports gtx_114_rx_p1]
# set_property -dict { PACKAGE_PIN U3   } [get_ports gtx_114_rx_n1]
# set_property -dict { PACKAGE_PIN R4   } [get_ports gtx_114_rx_p2]
# set_property -dict { PACKAGE_PIN R3   } [get_ports gtx_114_rx_n2]
# set_property -dict { PACKAGE_PIN P6   } [get_ports gtx_114_rx_p3]
# set_property -dict { PACKAGE_PIN P5   } [get_ports gtx_114_rx_n3]

# # GPIO: Currently paired up correctly, but with single-ended IOSTANDARD

# # TXP-TXN pairs
# set_property -dict { PACKAGE_PIN R18  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[0]}]
# set_property -dict { PACKAGE_PIN R19  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[0]}]
# set_property -dict { PACKAGE_PIN T20  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[1]}]
# set_property -dict { PACKAGE_PIN T21  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[1]}]
# set_property -dict { PACKAGE_PIN U19  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[2]}]
# set_property -dict { PACKAGE_PIN V19  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[2]}]
# set_property -dict { PACKAGE_PIN U17  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[3]}]
# set_property -dict { PACKAGE_PIN U18  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[3]}]
# set_property -dict { PACKAGE_PIN V17  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[4]}]
# set_property -dict { PACKAGE_PIN W17  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[4]}]
# set_property -dict { PACKAGE_PIN W18  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[5]}]
# set_property -dict { PACKAGE_PIN W19  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[5]}]

# # Middle pairs
# set_property -dict { PACKAGE_PIN T18  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[6]}]
# set_property -dict { PACKAGE_PIN T17  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[6]}]
# set_property -dict { PACKAGE_PIN T23  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[7]}]
# set_property -dict { PACKAGE_PIN R23  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[7]}]
# set_property -dict { PACKAGE_PIN V20  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[8]}]
# set_property -dict { PACKAGE_PIN U20  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[8]}]
# set_property -dict { PACKAGE_PIN W23  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[9]}]
# set_property -dict { PACKAGE_PIN W22  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[9]}]

# # RXP-RXN pairs
# set_property -dict { PACKAGE_PIN R24  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[10]}]
# set_property -dict { PACKAGE_PIN R25  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[10]}]
# set_property -dict { PACKAGE_PIN R26  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[11]}]
# set_property -dict { PACKAGE_PIN T27  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[11]}]
# set_property -dict { PACKAGE_PIN U27  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[12]}]
# set_property -dict { PACKAGE_PIN U28  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[12]}]
# set_property -dict { PACKAGE_PIN V24  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[13]}]
# set_property -dict { PACKAGE_PIN V25  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[13]}]
# set_property -dict { PACKAGE_PIN U29  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[14]}]
# set_property -dict { PACKAGE_PIN U30  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[14]}]
# set_property -dict { PACKAGE_PIN R20  IOSTANDARD LVCMOS25 } [get_ports {gpio_p[15]}]
# set_property -dict { PACKAGE_PIN R21  IOSTANDARD LVCMOS25 } [get_ports {gpio_n[15]}]
