########## --------- DDR3-B ------------##########
set_property -dict { PACKAGE_PIN W29  } [get_ports {ddr3_dq[0]}]
set_property -dict { PACKAGE_PIN Y29  } [get_ports {ddr3_dq[1]}]
set_property -dict { PACKAGE_PIN AB30 } [get_ports {ddr3_dq[2]}]
set_property -dict { PACKAGE_PIN AB29 } [get_ports {ddr3_dq[3]}]
set_property -dict { PACKAGE_PIN W28  } [get_ports {ddr3_dq[4]}]
set_property -dict { PACKAGE_PIN W26  } [get_ports {ddr3_dq[5]}]
set_property -dict { PACKAGE_PIN Y28  } [get_ports {ddr3_dq[6]}]
set_property -dict { PACKAGE_PIN AB28 } [get_ports {ddr3_dq[7]}]
set_property -dict { PACKAGE_PIN AA25 } [get_ports {ddr3_dq[8]}]
set_property -dict { PACKAGE_PIN AD27 } [get_ports {ddr3_dq[9]}]
set_property -dict { PACKAGE_PIN AB24 } [get_ports {ddr3_dq[10]}]
set_property -dict { PACKAGE_PIN AC24 } [get_ports {ddr3_dq[11]}]
set_property -dict { PACKAGE_PIN Y26  } [get_ports {ddr3_dq[12]}]
set_property -dict { PACKAGE_PIN Y25  } [get_ports {ddr3_dq[13]}]
set_property -dict { PACKAGE_PIN AA26 } [get_ports {ddr3_dq[14]}]
set_property -dict { PACKAGE_PIN AC26 } [get_ports {ddr3_dq[15]}]
set_property -dict { PACKAGE_PIN AD29 } [get_ports {ddr3_dq[16]}]
set_property -dict { PACKAGE_PIN AE30 } [get_ports {ddr3_dq[17]}]
set_property -dict { PACKAGE_PIN AE29 } [get_ports {ddr3_dq[18]}]
set_property -dict { PACKAGE_PIN AF30 } [get_ports {ddr3_dq[19]}]
set_property -dict { PACKAGE_PIN AD28 } [get_ports {ddr3_dq[20]}]
set_property -dict { PACKAGE_PIN AC27 } [get_ports {ddr3_dq[21]}]
set_property -dict { PACKAGE_PIN AF28 } [get_ports {ddr3_dq[22]}]
set_property -dict { PACKAGE_PIN AF27 } [get_ports {ddr3_dq[23]}]
set_property -dict { PACKAGE_PIN AG30 } [get_ports {ddr3_dq[24]}]
set_property -dict { PACKAGE_PIN AG29 } [get_ports {ddr3_dq[25]}]
set_property -dict { PACKAGE_PIN AH29 } [get_ports {ddr3_dq[26]}]
set_property -dict { PACKAGE_PIN AJ29 } [get_ports {ddr3_dq[27]}]
set_property -dict { PACKAGE_PIN AK30 } [get_ports {ddr3_dq[28]}]
set_property -dict { PACKAGE_PIN AK29 } [get_ports {ddr3_dq[29]}]
set_property -dict { PACKAGE_PIN AK28 } [get_ports {ddr3_dq[30]}]
set_property -dict { PACKAGE_PIN AG27 } [get_ports {ddr3_dq[31]}]
set_property -dict { PACKAGE_PIN AD18 } [get_ports {ddr3_dq[32]}]
set_property -dict { PACKAGE_PIN AD19 } [get_ports {ddr3_dq[33]}]
set_property -dict { PACKAGE_PIN AA18 } [get_ports {ddr3_dq[34]}]
set_property -dict { PACKAGE_PIN Y18  } [get_ports {ddr3_dq[35]}]
set_property -dict { PACKAGE_PIN AE18 } [get_ports {ddr3_dq[36]}]
set_property -dict { PACKAGE_PIN Y19  } [get_ports {ddr3_dq[37]}]
set_property -dict { PACKAGE_PIN AB17 } [get_ports {ddr3_dq[38]}]
set_property -dict { PACKAGE_PIN AA17 } [get_ports {ddr3_dq[39]}]
set_property -dict { PACKAGE_PIN AH20 } [get_ports {ddr3_dq[40]}]
set_property -dict { PACKAGE_PIN AH19 } [get_ports {ddr3_dq[41]}]
set_property -dict { PACKAGE_PIN AG19 } [get_ports {ddr3_dq[42]}]
set_property -dict { PACKAGE_PIN AF18 } [get_ports {ddr3_dq[43]}]
set_property -dict { PACKAGE_PIN AJ18 } [get_ports {ddr3_dq[44]}]
set_property -dict { PACKAGE_PIN AK18 } [get_ports {ddr3_dq[45]}]
set_property -dict { PACKAGE_PIN AJ17 } [get_ports {ddr3_dq[46]}]
set_property -dict { PACKAGE_PIN AJ16 } [get_ports {ddr3_dq[47]}]
set_property -dict { PACKAGE_PIN AF16 } [get_ports {ddr3_dq[48]}]
set_property -dict { PACKAGE_PIN AE16 } [get_ports {ddr3_dq[49]}]
set_property -dict { PACKAGE_PIN AE15 } [get_ports {ddr3_dq[50]}]
set_property -dict { PACKAGE_PIN AF15 } [get_ports {ddr3_dq[51]}]
set_property -dict { PACKAGE_PIN AC15 } [get_ports {ddr3_dq[52]}]
set_property -dict { PACKAGE_PIN AB15 } [get_ports {ddr3_dq[53]}]
set_property -dict { PACKAGE_PIN AC14 } [get_ports {ddr3_dq[54]}]
set_property -dict { PACKAGE_PIN AB14 } [get_ports {ddr3_dq[55]}]
set_property -dict { PACKAGE_PIN AH17 } [get_ports {ddr3_dq[56]}]
set_property -dict { PACKAGE_PIN AH16 } [get_ports {ddr3_dq[57]}]
set_property -dict { PACKAGE_PIN AK14 } [get_ports {ddr3_dq[58]}]
set_property -dict { PACKAGE_PIN AJ14 } [get_ports {ddr3_dq[59]}]
set_property -dict { PACKAGE_PIN AF17 } [get_ports {ddr3_dq[60]}]
set_property -dict { PACKAGE_PIN AG17 } [get_ports {ddr3_dq[61]}]
set_property -dict { PACKAGE_PIN AH15 } [get_ports {ddr3_dq[62]}]
set_property -dict { PACKAGE_PIN AH14 } [get_ports {ddr3_dq[63]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_dq[*]}]
set_property -dict { IN_TERM UNTUNED_SPLIT_50 } [get_ports {ddr3_dq[*]}]
set_property -dict { IOSTANDARD SSTL15 } [get_ports {ddr3_dq[*]}]

set_property -dict { PACKAGE_PIN AK24 } [get_ports {ddr3_addr[14]}]
set_property -dict { PACKAGE_PIN AD22 } [get_ports {ddr3_addr[13]}]
set_property -dict { PACKAGE_PIN AD21 } [get_ports {ddr3_addr[12]}]
set_property -dict { PACKAGE_PIN AK25 } [get_ports {ddr3_addr[11]}]
set_property -dict { PACKAGE_PIN AJ22 } [get_ports {ddr3_addr[10]}]
set_property -dict { PACKAGE_PIN AB23 } [get_ports {ddr3_addr[9]}]
set_property -dict { PACKAGE_PIN AE23 } [get_ports {ddr3_addr[8]}]
set_property -dict { PACKAGE_PIN AJ24 } [get_ports {ddr3_addr[7]}]
set_property -dict { PACKAGE_PIN AF23 } [get_ports {ddr3_addr[6]}]
set_property -dict { PACKAGE_PIN AD23 } [get_ports {ddr3_addr[5]}]
set_property -dict { PACKAGE_PIN AG23 } [get_ports {ddr3_addr[4]}]
set_property -dict { PACKAGE_PIN AJ26 } [get_ports {ddr3_addr[3]}]
set_property -dict { PACKAGE_PIN AF22 } [get_ports {ddr3_addr[2]}]
set_property -dict { PACKAGE_PIN AJ23 } [get_ports {ddr3_addr[1]}]
set_property -dict { PACKAGE_PIN AG22 } [get_ports {ddr3_addr[0]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_addr[*]}]
set_property -dict { IOSTANDARD SSTL15 } [get_ports {ddr3_addr[*]}]

set_property -dict { PACKAGE_PIN AC21 } [get_ports {ddr3_ba[2]}]
set_property -dict { PACKAGE_PIN AF21 } [get_ports {ddr3_ba[1]}]
set_property -dict { PACKAGE_PIN AK23 } [get_ports {ddr3_ba[0]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_ba[*]}]
set_property -dict { IOSTANDARD SSTL15 } [get_ports {ddr3_ba[*]}]

set_property -dict { PACKAGE_PIN AF20 SLEW FAST  IOSTANDARD SSTL15 } [get_ports ddr3_ras_n]
set_property -dict { PACKAGE_PIN AK21 SLEW FAST  IOSTANDARD SSTL15 } [get_ports ddr3_cas_n]
set_property -dict { PACKAGE_PIN AJ21 SLEW FAST  IOSTANDARD SSTL15 } [get_ports ddr3_we_n]
set_property -dict { PACKAGE_PIN Y21  SLEW FAST  IOSTANDARD LVCMOS15 } [get_ports ddr3_reset_n]
set_property -dict { PACKAGE_PIN AB22 SLEW FAST  IOSTANDARD SSTL15 } [get_ports {ddr3_cke[0]}]
set_property -dict { PACKAGE_PIN AG20  SLEW FAST  IOSTANDARD SSTL15 } [get_ports {ddr3_odt[0]}]
set_property -dict { PACKAGE_PIN AE21  SLEW FAST  IOSTANDARD SSTL15 } [get_ports {ddr3_cs_n[0]}]

set_property -dict { PACKAGE_PIN AA28 } [get_ports {ddr3_dm[0]}]
set_property -dict { PACKAGE_PIN AA27 } [get_ports {ddr3_dm[1]}]
set_property -dict { PACKAGE_PIN AE28 } [get_ports {ddr3_dm[2]}]
set_property -dict { PACKAGE_PIN AH30 } [get_ports {ddr3_dm[3]}]
set_property -dict { PACKAGE_PIN AB18 } [get_ports {ddr3_dm[4]}]
set_property -dict { PACKAGE_PIN AJ19 } [get_ports {ddr3_dm[5]}]
set_property -dict { PACKAGE_PIN AD14 } [get_ports {ddr3_dm[6]}]
set_property -dict { PACKAGE_PIN AK16 } [get_ports {ddr3_dm[7]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_dm[*]}]
set_property -dict { IOSTANDARD SSTL15 } [get_ports {ddr3_dm[*]}]

set_property -dict { PACKAGE_PIN AA30 } [get_ports {ddr3_dqs_n[0]}]
set_property -dict { PACKAGE_PIN Y30  } [get_ports {ddr3_dqs_p[0]}]
set_property -dict { PACKAGE_PIN AC25 } [get_ports {ddr3_dqs_n[1]}]
set_property -dict { PACKAGE_PIN AB25 } [get_ports {ddr3_dqs_p[1]}]
set_property -dict { PACKAGE_PIN AC30 } [get_ports {ddr3_dqs_n[2]}]
set_property -dict { PACKAGE_PIN AC29 } [get_ports {ddr3_dqs_p[2]}]
set_property -dict { PACKAGE_PIN AJ28 } [get_ports {ddr3_dqs_n[3]}]
set_property -dict { PACKAGE_PIN AJ27 } [get_ports {ddr3_dqs_p[3]}]
set_property -dict { PACKAGE_PIN AD17 } [get_ports {ddr3_dqs_n[4]}]
set_property -dict { PACKAGE_PIN AC17 } [get_ports {ddr3_dqs_p[4]}]
set_property -dict { PACKAGE_PIN AK20 } [get_ports {ddr3_dqs_n[5]}]
set_property -dict { PACKAGE_PIN AK19 } [get_ports {ddr3_dqs_p[5]}]
set_property -dict { PACKAGE_PIN AD16 } [get_ports {ddr3_dqs_n[6]}]
set_property -dict { PACKAGE_PIN AC16 } [get_ports {ddr3_dqs_p[6]}]
set_property -dict { PACKAGE_PIN AG15 } [get_ports {ddr3_dqs_n[7]}]
set_property -dict { PACKAGE_PIN AG14 } [get_ports {ddr3_dqs_p[7]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_dqs_n[*]}]
set_property -dict { IN_TERM UNTUNED_SPLIT_50 } [get_ports {ddr3_dqs_n[*]}]
set_property -dict { IOSTANDARD DIFF_SSTL15 } [get_ports {ddr3_dqs_n[*]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_dqs_p[*]}]
set_property -dict { IN_TERM UNTUNED_SPLIT_50 } [get_ports {ddr3_dqs_p[*]}]
set_property -dict { IOSTANDARD DIFF_SSTL15 } [get_ports {ddr3_dqs_p[*]}]

set_property -dict { PACKAGE_PIN AA23 SLEW FAST IOSTANDARD DIFF_SSTL15 } [get_ports {ddr3_ck_n[0]}]
set_property -dict { PACKAGE_PIN AA22 SLEW FAST IOSTANDARD DIFF_SSTL15 } [get_ports {ddr3_ck_p[0]}]
