########## --------- DDR3-A ------------##########
set_property -dict { PACKAGE_PIN A21  } [get_ports {ddr3_dq[0]}]
set_property -dict { PACKAGE_PIN A22  } [get_ports {ddr3_dq[1]}]
set_property -dict { PACKAGE_PIN A23  } [get_ports {ddr3_dq[2]}]
set_property -dict { PACKAGE_PIN B23  } [get_ports {ddr3_dq[3]}]
set_property -dict { PACKAGE_PIN B19  } [get_ports {ddr3_dq[4]}]
set_property -dict { PACKAGE_PIN C19  } [get_ports {ddr3_dq[5]}]
set_property -dict { PACKAGE_PIN A20  } [get_ports {ddr3_dq[6]}]
set_property -dict { PACKAGE_PIN B20  } [get_ports {ddr3_dq[7]}]
set_property -dict { PACKAGE_PIN C21  } [get_ports {ddr3_dq[8]}]
set_property -dict { PACKAGE_PIN C21  } [get_ports {ddr3_dq[9]}]
set_property -dict { PACKAGE_PIN C22  } [get_ports {ddr3_dq[10]}]
set_property -dict { PACKAGE_PIN D22  } [get_ports {ddr3_dq[11]}]
set_property -dict { PACKAGE_PIN E18  } [get_ports {ddr3_dq[12]}]
set_property -dict { PACKAGE_PIN D18  } [get_ports {ddr3_dq[13]}]
set_property -dict { PACKAGE_PIN E20  } [get_ports {ddr3_dq[14]}]
set_property -dict { PACKAGE_PIN E21  } [get_ports {ddr3_dq[15]}]
set_property -dict { PACKAGE_PIN G18  } [get_ports {ddr3_dq[16]}]
set_property -dict { PACKAGE_PIN F18  } [get_ports {ddr3_dq[17]}]
set_property -dict { PACKAGE_PIN G20  } [get_ports {ddr3_dq[18]}]
set_property -dict { PACKAGE_PIN F20  } [get_ports {ddr3_dq[19]}]
set_property -dict { PACKAGE_PIN H20  } [get_ports {ddr3_dq[20]}]
set_property -dict { PACKAGE_PIN G22  } [get_ports {ddr3_dq[21]}]
set_property -dict { PACKAGE_PIN G23  } [get_ports {ddr3_dq[22]}]
set_property -dict { PACKAGE_PIN F23  } [get_ports {ddr3_dq[23]}]
set_property -dict { PACKAGE_PIN L18  } [get_ports {ddr3_dq[24]}]
set_property -dict { PACKAGE_PIN J18  } [get_ports {ddr3_dq[25]}]
set_property -dict { PACKAGE_PIN J19  } [get_ports {ddr3_dq[26]}]
set_property -dict { PACKAGE_PIN K20  } [get_ports {ddr3_dq[27]}]
set_property -dict { PACKAGE_PIN J22  } [get_ports {ddr3_dq[28]}]
set_property -dict { PACKAGE_PIN H22  } [get_ports {ddr3_dq[29]}]
set_property -dict { PACKAGE_PIN K23  } [get_ports {ddr3_dq[30]}]
set_property -dict { PACKAGE_PIN J23  } [get_ports {ddr3_dq[31]}]
set_property -dict { PACKAGE_PIN N24  } [get_ports {ddr3_dq[32]}]
set_property -dict { PACKAGE_PIN N22  } [get_ports {ddr3_dq[33]}]
set_property -dict { PACKAGE_PIN P24  } [get_ports {ddr3_dq[34]}]
set_property -dict { PACKAGE_PIN P23  } [get_ports {ddr3_dq[35]}]
set_property -dict { PACKAGE_PIN L20  } [get_ports {ddr3_dq[36]}]
set_property -dict { PACKAGE_PIN M22  } [get_ports {ddr3_dq[37]}]
set_property -dict { PACKAGE_PIN M24  } [get_ports {ddr3_dq[38]}]
set_property -dict { PACKAGE_PIN N25  } [get_ports {ddr3_dq[39]}]
set_property -dict { PACKAGE_PIN M17  } [get_ports {ddr3_dq[40]}]
set_property -dict { PACKAGE_PIN N19  } [get_ports {ddr3_dq[41]}]
set_property -dict { PACKAGE_PIN N17  } [get_ports {ddr3_dq[42]}]
set_property -dict { PACKAGE_PIN P17  } [get_ports {ddr3_dq[43]}]
set_property -dict { PACKAGE_PIN N20  } [get_ports {ddr3_dq[44]}]
set_property -dict { PACKAGE_PIN N21  } [get_ports {ddr3_dq[45]}]
set_property -dict { PACKAGE_PIN P21  } [get_ports {ddr3_dq[46]}]
set_property -dict { PACKAGE_PIN P19  } [get_ports {ddr3_dq[47]}]
set_property -dict { PACKAGE_PIN K26  } [get_ports {ddr3_dq[48]}]
set_property -dict { PACKAGE_PIN K25  } [get_ports {ddr3_dq[49]}]
set_property -dict { PACKAGE_PIN L26  } [get_ports {ddr3_dq[50]}]
set_property -dict { PACKAGE_PIN L25  } [get_ports {ddr3_dq[51]}]
set_property -dict { PACKAGE_PIN M25  } [get_ports {ddr3_dq[52]}]
set_property -dict { PACKAGE_PIN N26  } [get_ports {ddr3_dq[53]}]
set_property -dict { PACKAGE_PIN P28  } [get_ports {ddr3_dq[54]}]
set_property -dict { PACKAGE_PIN P27  } [get_ports {ddr3_dq[55]}]
set_property -dict { PACKAGE_PIN L30  } [get_ports {ddr3_dq[56]}]
set_property -dict { PACKAGE_PIN M29  } [get_ports {ddr3_dq[57]}]
set_property -dict { PACKAGE_PIN P29  } [get_ports {ddr3_dq[58]}]
set_property -dict { PACKAGE_PIN R29  } [get_ports {ddr3_dq[59]}]
set_property -dict { PACKAGE_PIN K28  } [get_ports {ddr3_dq[60]}]
set_property -dict { PACKAGE_PIN K29  } [get_ports {ddr3_dq[61]}]
set_property -dict { PACKAGE_PIN K30  } [get_ports {ddr3_dq[62]}]
set_property -dict { PACKAGE_PIN M28  } [get_ports {ddr3_dq[63]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_dq[*]}]
set_property -dict { IN_TERM UNTUNED_SPLIT_50 } [get_ports {ddr3_dq[*]}]
set_property -dict { IOSTANDARD SSTL15 } [get_ports {ddr3_dq[*]}]

set_property -dict { PACKAGE_PIN F25 } [get_ports {ddr3_addr[14]}]
set_property -dict { PACKAGE_PIN H29 } [get_ports {ddr3_addr[13]}]
set_property -dict { PACKAGE_PIN A28 } [get_ports {ddr3_addr[12]}]
set_property -dict { PACKAGE_PIN E26 } [get_ports {ddr3_addr[11]}]
set_property -dict { PACKAGE_PIN E30 } [get_ports {ddr3_addr[10]}]
set_property -dict { PACKAGE_PIN B30 } [get_ports {ddr3_addr[9]}]
set_property -dict { PACKAGE_PIN C29 } [get_ports {ddr3_addr[8]}]
set_property -dict { PACKAGE_PIN B28 } [get_ports {ddr3_addr[7]}]
set_property -dict { PACKAGE_PIN A30 } [get_ports {ddr3_addr[6]}]
set_property -dict { PACKAGE_PIN C30 } [get_ports {ddr3_addr[5]}]
set_property -dict { PACKAGE_PIN B29 } [get_ports {ddr3_addr[4]}]
set_property -dict { PACKAGE_PIN D29 } [get_ports {ddr3_addr[3]}]
set_property -dict { PACKAGE_PIN F26 } [get_ports {ddr3_addr[2]}]
set_property -dict { PACKAGE_PIN E29 } [get_ports {ddr3_addr[1]}]
set_property -dict { PACKAGE_PIN F28 } [get_ports {ddr3_addr[0]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_addr[*]}]
set_property -dict { IOSTANDARD SSTL15 } [get_ports {ddr3_addr[*]}]

set_property -dict { PACKAGE_PIN E28 } [get_ports {ddr3_ba[2]}]
set_property -dict { PACKAGE_PIN G28 } [get_ports {ddr3_ba[1]}]
set_property -dict { PACKAGE_PIN F30 } [get_ports {ddr3_ba[0]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_ba[*]}]
set_property -dict { IOSTANDARD SSTL15 } [get_ports {ddr3_ba[*]}]

set_property -dict { PACKAGE_PIN H27  SLEW FAST  IOSTANDARD SSTL15 } [get_ports ddr3_ras_n]
set_property -dict { PACKAGE_PIN G30  SLEW FAST  IOSTANDARD SSTL15 } [get_ports ddr3_cas_n]
set_property -dict { PACKAGE_PIN G29  SLEW FAST  IOSTANDARD SSTL15 } [get_ports ddr3_we_n]
set_property -dict { PACKAGE_PIN F27  SLEW FAST  IOSTANDARD LVCMOS15 } [get_ports ddr3_reset_n]
set_property -dict { PACKAGE_PIN G25  SLEW FAST  IOSTANDARD SSTL15 } [get_ports {ddr3_cke[0]}]
set_property -dict { PACKAGE_PIN J28  SLEW FAST  IOSTANDARD SSTL15 } [get_ports {ddr3_odt[0]}]
set_property -dict { PACKAGE_PIN H30  SLEW FAST  IOSTANDARD SSTL15 } [get_ports {ddr3_cs_n[0]}]

set_property -dict { PACKAGE_PIN B22 } [get_ports {ddr3_dm[0]}]
set_property -dict { PACKAGE_PIN E19 } [get_ports {ddr3_dm[1]}]
set_property -dict { PACKAGE_PIN F22 } [get_ports {ddr3_dm[2]}]
set_property -dict { PACKAGE_PIN K19 } [get_ports {ddr3_dm[3]}]
set_property -dict { PACKAGE_PIN M23 } [get_ports {ddr3_dm[4]}]
set_property -dict { PACKAGE_PIN P18 } [get_ports {ddr3_dm[5]}]
set_property -dict { PACKAGE_PIN P26 } [get_ports {ddr3_dm[6]}]
set_property -dict { PACKAGE_PIN N29 } [get_ports {ddr3_dm[7]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_dm[*]}]
set_property -dict { IOSTANDARD SSTL15 } [get_ports {ddr3_dm[*]}]

set_property -dict { PACKAGE_PIN A18 } [get_ports {ddr3_dqs_n[0]}]
set_property -dict { PACKAGE_PIN B18 } [get_ports {ddr3_dqs_p[0]}]
set_property -dict { PACKAGE_PIN D23 } [get_ports {ddr3_dqs_n[1]}]
set_property -dict { PACKAGE_PIN E23 } [get_ports {ddr3_dqs_p[1]}]
set_property -dict { PACKAGE_PIN G19 } [get_ports {ddr3_dqs_n[2]}]
set_property -dict { PACKAGE_PIN H19 } [get_ports {ddr3_dqs_p[2]}]
set_property -dict { PACKAGE_PIN J21 } [get_ports {ddr3_dqs_n[3]}]
set_property -dict { PACKAGE_PIN K21 } [get_ports {ddr3_dqs_p[3]}]
set_property -dict { PACKAGE_PIN K24 } [get_ports {ddr3_dqs_n[4]}]
set_property -dict { PACKAGE_PIN L23 } [get_ports {ddr3_dqs_p[4]}]
set_property -dict { PACKAGE_PIN M19 } [get_ports {ddr3_dqs_n[5]}]
set_property -dict { PACKAGE_PIN M18 } [get_ports {ddr3_dqs_p[5]}]
set_property -dict { PACKAGE_PIN M27 } [get_ports {ddr3_dqs_n[6]}]
set_property -dict { PACKAGE_PIN N27 } [get_ports {ddr3_dqs_p[6]}]
set_property -dict { PACKAGE_PIN M30 } [get_ports {ddr3_dqs_n[7]}]
set_property -dict { PACKAGE_PIN N30 } [get_ports {ddr3_dqs_p[7]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_dqs_n[*]}]
set_property -dict { IN_TERM UNTUNED_SPLIT_50 } [get_ports {ddr3_dqs_n[*]}]
set_property -dict { IOSTANDARD DIFF_SSTL15 } [get_ports {ddr3_dqs_n[*]}]
set_property -dict { SLEW FAST } [get_ports {ddr3_dqs_p[*]}]
set_property -dict { IN_TERM UNTUNED_SPLIT_50 } [get_ports {ddr3_dqs_p[*]}]
set_property -dict { IOSTANDARD DIFF_SSTL15 } [get_ports {ddr3_dqs_p[*]}]

set_property -dict { PACKAGE_PIN J27  SLEW FAST IOSTANDARD DIFF_SSTL15 } [get_ports {ddr3_ck_n[0]}]
set_property -dict { PACKAGE_PIN J26  SLEW FAST IOSTANDARD DIFF_SSTL15 } [get_ports {ddr3_ck_p[0]}]
